/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSsoUserInfoRouteImport } from './routes/api/sso/userInfo'
import { Route as ApiSsoLogoutRouteImport } from './routes/api/sso/logout'
import { Route as ApiSsoLoginRouteImport } from './routes/api/sso/login'
import { Route as ApiSsoCallbackRouteImport } from './routes/api/sso/callback'
import { Route as ApiRtmTokenRouteImport } from './routes/api/rtm/token'
import { Route as ApiRtcTokenRouteImport } from './routes/api/rtc/token'
import { Route as ApiMobileViewerSessionRouteImport } from './routes/api/mobile-viewer/session'
import { Route as ApiMobileViewerLinkRouteImport } from './routes/api/mobile-viewer/link'
import { Route as ApiSttGroupSessionVttRouteImport } from './routes/api/stt-group/session/vtt'
import { Route as ApiSttGroupSessionStopRouteImport } from './routes/api/stt-group/session/stop'
import { Route as ApiSttGroupSessionStatusRouteImport } from './routes/api/stt-group/session/status'
import { Route as ApiSttGroupSessionStartRouteImport } from './routes/api/stt-group/session/start'

const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSsoUserInfoRoute = ApiSsoUserInfoRouteImport.update({
  id: '/api/sso/userInfo',
  path: '/api/sso/userInfo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSsoLogoutRoute = ApiSsoLogoutRouteImport.update({
  id: '/api/sso/logout',
  path: '/api/sso/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSsoLoginRoute = ApiSsoLoginRouteImport.update({
  id: '/api/sso/login',
  path: '/api/sso/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSsoCallbackRoute = ApiSsoCallbackRouteImport.update({
  id: '/api/sso/callback',
  path: '/api/sso/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtmTokenRoute = ApiRtmTokenRouteImport.update({
  id: '/api/rtm/token',
  path: '/api/rtm/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcTokenRoute = ApiRtcTokenRouteImport.update({
  id: '/api/rtc/token',
  path: '/api/rtc/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileViewerSessionRoute = ApiMobileViewerSessionRouteImport.update({
  id: '/api/mobile-viewer/session',
  path: '/api/mobile-viewer/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileViewerLinkRoute = ApiMobileViewerLinkRouteImport.update({
  id: '/api/mobile-viewer/link',
  path: '/api/mobile-viewer/link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttGroupSessionVttRoute = ApiSttGroupSessionVttRouteImport.update({
  id: '/api/stt-group/session/vtt',
  path: '/api/stt-group/session/vtt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttGroupSessionStopRoute = ApiSttGroupSessionStopRouteImport.update({
  id: '/api/stt-group/session/stop',
  path: '/api/stt-group/session/stop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttGroupSessionStatusRoute =
  ApiSttGroupSessionStatusRouteImport.update({
    id: '/api/stt-group/session/status',
    path: '/api/stt-group/session/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSttGroupSessionStartRoute = ApiSttGroupSessionStartRouteImport.update({
  id: '/api/stt-group/session/start',
  path: '/api/stt-group/session/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/mobile': typeof MobileRoute
  '/api/mobile-viewer/link': typeof ApiMobileViewerLinkRoute
  '/api/mobile-viewer/session': typeof ApiMobileViewerSessionRoute
  '/api/rtc/token': typeof ApiRtcTokenRoute
  '/api/rtm/token': typeof ApiRtmTokenRoute
  '/api/sso/callback': typeof ApiSsoCallbackRoute
  '/api/sso/login': typeof ApiSsoLoginRoute
  '/api/sso/logout': typeof ApiSsoLogoutRoute
  '/api/sso/userInfo': typeof ApiSsoUserInfoRoute
  '/api/stt-group/session/start': typeof ApiSttGroupSessionStartRoute
  '/api/stt-group/session/status': typeof ApiSttGroupSessionStatusRoute
  '/api/stt-group/session/stop': typeof ApiSttGroupSessionStopRoute
  '/api/stt-group/session/vtt': typeof ApiSttGroupSessionVttRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/mobile': typeof MobileRoute
  '/api/mobile-viewer/link': typeof ApiMobileViewerLinkRoute
  '/api/mobile-viewer/session': typeof ApiMobileViewerSessionRoute
  '/api/rtc/token': typeof ApiRtcTokenRoute
  '/api/rtm/token': typeof ApiRtmTokenRoute
  '/api/sso/callback': typeof ApiSsoCallbackRoute
  '/api/sso/login': typeof ApiSsoLoginRoute
  '/api/sso/logout': typeof ApiSsoLogoutRoute
  '/api/sso/userInfo': typeof ApiSsoUserInfoRoute
  '/api/stt-group/session/start': typeof ApiSttGroupSessionStartRoute
  '/api/stt-group/session/status': typeof ApiSttGroupSessionStatusRoute
  '/api/stt-group/session/stop': typeof ApiSttGroupSessionStopRoute
  '/api/stt-group/session/vtt': typeof ApiSttGroupSessionVttRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/mobile': typeof MobileRoute
  '/api/mobile-viewer/link': typeof ApiMobileViewerLinkRoute
  '/api/mobile-viewer/session': typeof ApiMobileViewerSessionRoute
  '/api/rtc/token': typeof ApiRtcTokenRoute
  '/api/rtm/token': typeof ApiRtmTokenRoute
  '/api/sso/callback': typeof ApiSsoCallbackRoute
  '/api/sso/login': typeof ApiSsoLoginRoute
  '/api/sso/logout': typeof ApiSsoLogoutRoute
  '/api/sso/userInfo': typeof ApiSsoUserInfoRoute
  '/api/stt-group/session/start': typeof ApiSttGroupSessionStartRoute
  '/api/stt-group/session/status': typeof ApiSttGroupSessionStatusRoute
  '/api/stt-group/session/stop': typeof ApiSttGroupSessionStopRoute
  '/api/stt-group/session/vtt': typeof ApiSttGroupSessionVttRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/mobile'
    | '/api/mobile-viewer/link'
    | '/api/mobile-viewer/session'
    | '/api/rtc/token'
    | '/api/rtm/token'
    | '/api/sso/callback'
    | '/api/sso/login'
    | '/api/sso/logout'
    | '/api/sso/userInfo'
    | '/api/stt-group/session/start'
    | '/api/stt-group/session/status'
    | '/api/stt-group/session/stop'
    | '/api/stt-group/session/vtt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/mobile'
    | '/api/mobile-viewer/link'
    | '/api/mobile-viewer/session'
    | '/api/rtc/token'
    | '/api/rtm/token'
    | '/api/sso/callback'
    | '/api/sso/login'
    | '/api/sso/logout'
    | '/api/sso/userInfo'
    | '/api/stt-group/session/start'
    | '/api/stt-group/session/status'
    | '/api/stt-group/session/stop'
    | '/api/stt-group/session/vtt'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/mobile'
    | '/api/mobile-viewer/link'
    | '/api/mobile-viewer/session'
    | '/api/rtc/token'
    | '/api/rtm/token'
    | '/api/sso/callback'
    | '/api/sso/login'
    | '/api/sso/logout'
    | '/api/sso/userInfo'
    | '/api/stt-group/session/start'
    | '/api/stt-group/session/status'
    | '/api/stt-group/session/stop'
    | '/api/stt-group/session/vtt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  MobileRoute: typeof MobileRoute
  ApiMobileViewerLinkRoute: typeof ApiMobileViewerLinkRoute
  ApiMobileViewerSessionRoute: typeof ApiMobileViewerSessionRoute
  ApiRtcTokenRoute: typeof ApiRtcTokenRoute
  ApiRtmTokenRoute: typeof ApiRtmTokenRoute
  ApiSsoCallbackRoute: typeof ApiSsoCallbackRoute
  ApiSsoLoginRoute: typeof ApiSsoLoginRoute
  ApiSsoLogoutRoute: typeof ApiSsoLogoutRoute
  ApiSsoUserInfoRoute: typeof ApiSsoUserInfoRoute
  ApiSttGroupSessionStartRoute: typeof ApiSttGroupSessionStartRoute
  ApiSttGroupSessionStatusRoute: typeof ApiSttGroupSessionStatusRoute
  ApiSttGroupSessionStopRoute: typeof ApiSttGroupSessionStopRoute
  ApiSttGroupSessionVttRoute: typeof ApiSttGroupSessionVttRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sso/userInfo': {
      id: '/api/sso/userInfo'
      path: '/api/sso/userInfo'
      fullPath: '/api/sso/userInfo'
      preLoaderRoute: typeof ApiSsoUserInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sso/logout': {
      id: '/api/sso/logout'
      path: '/api/sso/logout'
      fullPath: '/api/sso/logout'
      preLoaderRoute: typeof ApiSsoLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sso/login': {
      id: '/api/sso/login'
      path: '/api/sso/login'
      fullPath: '/api/sso/login'
      preLoaderRoute: typeof ApiSsoLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sso/callback': {
      id: '/api/sso/callback'
      path: '/api/sso/callback'
      fullPath: '/api/sso/callback'
      preLoaderRoute: typeof ApiSsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtm/token': {
      id: '/api/rtm/token'
      path: '/api/rtm/token'
      fullPath: '/api/rtm/token'
      preLoaderRoute: typeof ApiRtmTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc/token': {
      id: '/api/rtc/token'
      path: '/api/rtc/token'
      fullPath: '/api/rtc/token'
      preLoaderRoute: typeof ApiRtcTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile-viewer/session': {
      id: '/api/mobile-viewer/session'
      path: '/api/mobile-viewer/session'
      fullPath: '/api/mobile-viewer/session'
      preLoaderRoute: typeof ApiMobileViewerSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile-viewer/link': {
      id: '/api/mobile-viewer/link'
      path: '/api/mobile-viewer/link'
      fullPath: '/api/mobile-viewer/link'
      preLoaderRoute: typeof ApiMobileViewerLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt-group/session/vtt': {
      id: '/api/stt-group/session/vtt'
      path: '/api/stt-group/session/vtt'
      fullPath: '/api/stt-group/session/vtt'
      preLoaderRoute: typeof ApiSttGroupSessionVttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt-group/session/stop': {
      id: '/api/stt-group/session/stop'
      path: '/api/stt-group/session/stop'
      fullPath: '/api/stt-group/session/stop'
      preLoaderRoute: typeof ApiSttGroupSessionStopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt-group/session/status': {
      id: '/api/stt-group/session/status'
      path: '/api/stt-group/session/status'
      fullPath: '/api/stt-group/session/status'
      preLoaderRoute: typeof ApiSttGroupSessionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt-group/session/start': {
      id: '/api/stt-group/session/start'
      path: '/api/stt-group/session/start'
      fullPath: '/api/stt-group/session/start'
      preLoaderRoute: typeof ApiSttGroupSessionStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  MobileRoute: MobileRoute,
  ApiMobileViewerLinkRoute: ApiMobileViewerLinkRoute,
  ApiMobileViewerSessionRoute: ApiMobileViewerSessionRoute,
  ApiRtcTokenRoute: ApiRtcTokenRoute,
  ApiRtmTokenRoute: ApiRtmTokenRoute,
  ApiSsoCallbackRoute: ApiSsoCallbackRoute,
  ApiSsoLoginRoute: ApiSsoLoginRoute,
  ApiSsoLogoutRoute: ApiSsoLogoutRoute,
  ApiSsoUserInfoRoute: ApiSsoUserInfoRoute,
  ApiSttGroupSessionStartRoute: ApiSttGroupSessionStartRoute,
  ApiSttGroupSessionStatusRoute: ApiSttGroupSessionStatusRoute,
  ApiSttGroupSessionStopRoute: ApiSttGroupSessionStopRoute,
  ApiSttGroupSessionVttRoute: ApiSttGroupSessionVttRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
